hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  #joints:
    #- arm_roll_joint
    #- arm_flex_joint
    #- elbow_flex_joint
    #- wrist_flex_joint
    #- hand_motor_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

xtion_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - xtion_pan_joint
    - xtion_tilt_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

dynamixel_port:
  port_name: "/dev/dynamixel"
  baud_rate: 115200
  joints:
    - arm_roll_joint
    - arm_flex_joint
    - elbow_flex_joint
    - wrist_flex_joint
    - hand_motor_joint
    - xtion_pan_joint
    - xtion_tilt_joint
  arm_roll_joint: {id: 16, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300}
  arm_flex_joint: {id: 17, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300 }
  elbow_flex_joint: {id: 18, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300 }
  wrist_flex_joint: {id: 19, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300 }
  hand_motor_joint: {id: 20, center: 2048, home: 3000, mode: 5, vel: 0, acc: 0, pos_i_gain: 0, lim: 200 }
  xtion_pan_joint: {id: 1, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300 }
  xtion_tilt_joint: {id: 2, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300 }