hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_roll_joint
    - arm_flex_joint
    - elbow_flex_joint
    - wrist_flex_joint
    - hand_motor_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

xtion_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - xtion_tilt_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true