/**/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    head_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/head_position_controller:
  ros__parameters:
    joints:
      - head_camera_pan_joint
      - head_camera_tilt_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/arm_position_controller:
  ros__parameters:
    joints:
      - arm_shoulder_roll_joint
      - arm_shoulder_pitch_joint
      - arm_shoulder_pitch_sub_joint
      - arm_elbow_pitch_joint
      - arm_forearm_roll_joint
      - arm_wrist_pitch_joint
      - arm_wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

/**/hand_position_controller:
  ros__parameters:
    joints:
      - hand_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

