dynamixel_port:
  port_name: "/dev/input/dx_upper"
  baud_rate: 1000000
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_1_tilt_joint
    - arm_shoulder_2_tilt_joint
    - arm_elbow_1_tilt_joint
    - arm_elbow_2_tilt_joint
    - arm_wrist_tilt_joint
    - hand_joint
    - head_camera_pan_joint
    - head_camera_tilt_joint

  arm_shoulder_pan_joint:    {id: 10, center: 2048, home:  0.0,    mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_shoulder_1_tilt_joint: {id: 11, center: 2048, home:  1.5708, mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_shoulder_2_tilt_joint: {id: 12, center: 2048, home: -1.5708, mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_elbow_1_tilt_joint:    {id: 13, center: 2048, home: -1.40,   mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_elbow_2_tilt_joint:    {id: 14, center: 2048, home:  1.40,   mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_wrist_tilt_joint:      {id: 15, center: 2048, home: -0.17,   mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  hand_joint:                {id: 16, center: 2048, home:  0.0,    mode: 5, vel: 128, acc: 0, pos_d_gain: 300,  pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1, lim: 100 }
  head_camera_pan_joint:     {id: 21, center: 2048, home:  0.0,    mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  head_camera_tilt_joint:    {id: 22, center: 2048, home:  0.0,    mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }