dynamixel_port:
  port_name: "/dev/input/dx_upper"
  baud_rate: 1000000
  joints:
    - head_camera_pan_joint
    - head_camera_tilt_joint
  head_camera_pan_joint:     {id: 21, center: 2048, home:  0.0,    mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }
  head_camera_tilt_joint:    {id: 22, center: 2048, home:  0.0,    mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain: 5, pos_p_gain: 1000, gear_ratio: 1 }