# Default initial positions for sobit_edu's ros2_control fake system

initial_positions:
  arm_elbow_pitch_joint: 0
  arm_forearm_roll_joint: 0
  arm_shoulder_pitch_joint: 0
  arm_shoulder_roll_joint: 0
  arm_wrist_pitch_joint: 0
  arm_wrist_roll_joint: 0
  hand_joint: 0
  # virtual_base_joint: 0