planning_plugins:
  - pilz_industrial_motion_planner/CommandPlanner
request_adapters:
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/CheckForStackedConstraints
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath
default_planner_config: PTP
capabilities: >-
  pilz_industrial_motion_planner/MoveGroupSequenceAction
  pilz_industrial_motion_planner/MoveGroupSequenceService
